### ISSUE TITLE
Use NodeAtlas with Proxy

### ISSUE THREAD

**Issue by PierreAmmeloot** [Haeresis/NodeAtlas#133]
Hello, I wan't use NodeAtlas with a proxy.

Do you have any doc and exemple for this?

Pierre

**Comment by Haeresis** [comment]
[From the documentation](https://node-atlas.js.org/environnement-de-production.html#proxy), you could use [Bouncy]() but there is a lack of support. 

So instead you could use [node-http-proxy](https://www.npmjs.com/package/http-proxy). I will provide some code in the documentation to replace Bouncy!
